name: Norminette

on:
  push:

jobs:
  check-norminette:
    name: Norminette
    runs-on: ubuntu-latest
    steps:
      - name: Clone projet to current dir
        uses: actions/checkout@v3

      - name: Norminette
        uses: 42School/norminette@3.3.59
        with:
          args: '-RCheckForbiddenSourceHeader'
  check-compilation:
    name: Run make
    runs-on: ubuntu-latest
    needs: check-norminette
    steps:
      - name: Clone projet to current dir
        uses: actions/checkout@v3
      
      - name: Compile
        run: ls
        continue-on-error: false